language: go
go:
  - master

before_install:
  - go get -u -d gocv.io/x/gocv
  - cd $GOPATH/src/gocv.io/x/gocv
  - make install

install:
  - true

script:
  - go test -v ./...

notifications:
  slack: grab:OVbEkJH3R10nkyKfwT996cB5
